apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-staraus1-persistent-storage
  namespace: staraus-test1
  labels:
    app: staraust1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 6Gi
