# create a service for wordpress
apiVersion: v1
kind: Service
metadata:
  name: staraust1
  namespace: staraus-test1
  labels:
    app: staraust1
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32010

  selector:
    app: staraust1
    tier: frontend
